# -*- coding: utf-8 -*-
"""Simulation_Plots

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rniX8DP3OfKJFVGON0Zfc_CfW8GU-HqO
"""

import numpy as np
import matplotlib.pyplot as plt

# Define the data
central = [0.22e-4, 0.1677e-4, 0.0732e-4]
peripheral = [0.1130e-4, 0.0749e-4, 0.0327e-4]

# Define colors for each pair of elements
colors = ['b', 'g', 'r']

# Combine central and peripheral data
combined_data = central + peripheral

# Define labels for central and peripheral data
labels = ['Central Reference', 'Central IEEE802.11ba', 'Central Customized', 'Peripheral Reference', 'Peripheral IEEE802.11ba', 'Peripheral Customized']

# Plot the bar graph with custom colors and spacing
bars = plt.bar(np.arange(len(combined_data)), combined_data, color=[colors[i % 3] for i in range(len(combined_data))])

# Create a legend with the same label names
plt.legend(bars, labels)

# Add labels and title
plt.xlabel('Elements')
plt.ylabel('Value')
plt.title('Power Consumption in Peer-to-Peer Communication')

plt.savefig('bar.png', format='png')

# Show the plot
plt.show()